// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Cox_general
Rcpp::List Cox_general(arma::vec Time, arma::vec t, arma::vec Delta, arma::vec C, arma::field<arma::vec> V, arma::field<arma::vec> S, arma::mat X, arma::vec m, arma::vec VacTime, arma::vec FirstInfTime, arma::vec dimension, int infection_ind, int interact_ind, arma::field<arma::vec> knots, arma::mat ResMat, double eps, int MaxIter, bool constantVE, bool interact, double cutoff);
RcppExport SEXP _DOVE3_Cox_general(SEXP TimeSEXP, SEXP tSEXP, SEXP DeltaSEXP, SEXP CSEXP, SEXP VSEXP, SEXP SSEXP, SEXP XSEXP, SEXP mSEXP, SEXP VacTimeSEXP, SEXP FirstInfTimeSEXP, SEXP dimensionSEXP, SEXP infection_indSEXP, SEXP interact_indSEXP, SEXP knotsSEXP, SEXP ResMatSEXP, SEXP epsSEXP, SEXP MaxIterSEXP, SEXP constantVESEXP, SEXP interactSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VacTime(VacTimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type FirstInfTime(FirstInfTimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< int >::type infection_ind(infection_indSEXP);
    Rcpp::traits::input_parameter< int >::type interact_ind(interact_indSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ResMat(ResMatSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type MaxIter(MaxIterSEXP);
    Rcpp::traits::input_parameter< bool >::type constantVE(constantVESEXP);
    Rcpp::traits::input_parameter< bool >::type interact(interactSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(Cox_general(Time, t, Delta, C, V, S, X, m, VacTime, FirstInfTime, dimension, infection_ind, interact_ind, knots, ResMat, eps, MaxIter, constantVE, interact, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// computeList
arma::field<arma::vec> computeList(arma::field<arma::vec> object, arma::field<arma::vec> add, arma::vec index);
RcppExport SEXP _DOVE3_computeList(SEXP objectSEXP, SEXP addSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type object(objectSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type add(addSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(computeList(object, add, index));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DOVE3_Cox_general", (DL_FUNC) &_DOVE3_Cox_general, 20},
    {"_DOVE3_computeList", (DL_FUNC) &_DOVE3_computeList, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DOVE3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
