# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cox_general <- function(Time, t, Delta, C, V, S, X, m, VacTime, FirstInfTime, dimension, infection_ind, interact_ind, knots, ResMat, eps, MaxIter, constantVE, interact, cutoff) {
    .Call('_DOVE3_Cox_general', PACKAGE = 'DOVE3', Time, t, Delta, C, V, S, X, m, VacTime, FirstInfTime, dimension, infection_ind, interact_ind, knots, ResMat, eps, MaxIter, constantVE, interact, cutoff)
}

computeList <- function(object, add, index) {
    .Call('_DOVE3_computeList', PACKAGE = 'DOVE3', object, add, index)
}

